[package]
name    = "zbot"
version = "0.1.5"
authors = ["zxv <zxv@tfwno.gf>"]
build   = "build.rs"

[dependencies]
irc          = "0.13"
serenity     = "0.5.1"
toml         = "0.4"
serde        = "1.0"
serde_derive = "1.0"
rb           = "0.3.2"
rusqlite     = "0.13.0"
rand         = "0.5.0"
regex        = "1.0.0"
